### PR TITLE
Change react-modal-overlay z-index so that it will be on top of new ui

### PR DESCRIPTION
**Pull request by bryanj0410**
new Juno ui sidenav z-index is 900 and the header z-index is 1000.
putting the react modal overlay z-index to 1100 so that it will cover all of the page.

### CODE REVIEW

**Comment by nixon-by** [comment]
@bryanj0410 
Please try to set z indexes up to 10. i suppose it will work. 
No need to define those big values, because eventually we will use 999999.. values

**Comment by bryanj0410** [comment]
@nixon-by I agree, the only reason for the big number on the modal is because the new juno design has the big numbers on the header, footer, and sidenav.

**Comment by nixon-by** [comment]
@bryanj0410  Maybe it's time to change z-indexes in the new design, till is causes new DOM objects with the huge z-index values?

**Comment by bryanj0410** [comment]
Closing this because I found and changed the z-index in the new design for the header, footer, and sidenav.

**Pull request closed without merging**
